version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: taidang
      POSTGRES_PASSWORD: taidang123
      POSTGRES_DB: clv_jwat_taidang

